# 2.3 Lab: Introduction to Python

## 2.3.2 Basic Commands

In [4]:
print("fit a model with", 11, "variables")

fit a model with 11 variables


In [5]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [6]:
3 + 5

8

In [7]:
"hello" + " " + "world"

'hello world'

In [8]:
x = [3, 4, 5]
x

[3, 4, 5]

In [9]:
y = [4, 9, 7]
x + y

[3, 4, 5, 4, 9, 7]

## 2.3.3 Introduction to Numerical Python

In [10]:
import numpy as np

In [11]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [12]:
x + y

array([ 7, 13, 12])

In [13]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [14]:
x.ndim

2

In [15]:
x.dtype

dtype('int64')

In [16]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [17]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [18]:
np.array([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [19]:
x.shape

(2, 2)

In [22]:
x = np.array([1, 2, 3, 4])
x.sum()

np.int64(10)

In [23]:
x = np.array([1, 2, 3, 4])
np.sum(x)

np.int64(10)

In [24]:
x = np.array([1, 2, 3, 4, 5, 6])
print("beginning x: \n", x)
x_reshape = x.reshape((2, 3))
print("reshaped x: \n", x_reshape)

beginning x: 
 [1 2 3 4 5 6]
reshaped x: 
 [[1 2 3]
 [4 5 6]]


In [25]:
x_reshape[0, 0]

np.int64(1)

In [26]:
x_reshape[1, 2]

np.int64(6)

In [28]:
print("x before we modify x_reshape:\n", x)
print("x_reshpe before we modify x_reshape:\n", x_reshape)
x_reshape[0, 0] = 5
print("x_reshape after we modify its top left element:\n", x_reshape)
print("x after we modify top left element of x_reshape:\n", x)

x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshpe before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


In [29]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

In [30]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [31]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [32]:
x**2

array([25,  4,  9, 16, 25, 36])

In [33]:
x**0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [34]:
x = np.random.normal(size=50)

In [35]:
x

array([-0.76068366, -0.26554162,  0.05593205,  0.65043268,  0.9933212 ,
       -1.74118449,  1.5548715 , -1.04280116, -0.24654185,  0.78855435,
        0.04333475,  1.38726235, -1.18465997,  2.07786763,  0.08208482,
       -0.45957409, -0.75509855, -1.36273711,  1.84008268, -0.34369843,
        0.57568913,  0.17384271,  0.4244663 ,  0.85852507, -0.39529582,
        0.53600831,  1.30940571, -1.18183799, -0.53618403,  0.44935051,
       -1.47426593,  0.58540733, -0.34025753,  0.66309602, -0.05863297,
        1.35940181,  0.69436645,  0.10444473,  0.77600615,  2.7367914 ,
       -1.19635946,  0.16711418,  0.37933893,  0.04897658,  0.59106398,
        0.51511423,  0.70844209, -0.88252286, -0.29132013, -0.3985545 ])

In [36]:
y = x + np.random.normal(loc=50, scale=1, size=50)

In [37]:
np.corrcoef(x, y)

array([[1.        , 0.60458027],
       [0.60458027, 1.        ]])

In [38]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2))

[2.2121699  1.16021579]
[ 4.42656928 -1.23484637]


In [39]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))

rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [40]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(np.float64(-0.1126795190952861), np.float64(-0.1126795190952861))

In [42]:
np.var(y), y.var(), np.mean((y - y.mean())**2)

(np.float64(2.7243406406465125),
 np.float64(2.7243406406465125),
 np.float64(2.7243406406465125))

In [43]:
np.var?

Signature:      
np.var(
    a,
    axis=None,
    dtype=None,
    out=None,
    ddof=0,
    keepdims=<no value>,
    *,
    where=<no value>,
    mean=<no value>,
    correction=<no value>,
)
Call signature:  np.var(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function var at 0x1043ded30>
File:            ~/Library/Python/3.9/lib/python/site-packages/numpy/_core/fromnumeric.py
Docstring:      
Compute the variance along the specified axis.

Returns the variance of the array elements, a measure of the spread of a
distribution.  The variance is computed for the flattened array by
default, otherwise over the specified axis.

Parameters
----------
a : array_like
    Array containing numbers whose variance is desired.  If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the variance is computed.  The default is to
    compute the variance of the flattened array.

    .. versionadde

In [44]:
np.sqrt(np.var(y)), np.std(y)

(np.float64(1.6505576756498128), np.float64(1.6505576756498128))

In [45]:
X = rng.standard_normal((10, 3))
X

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])

## 2.3.4 Graphics